create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  address text not null default '',
  area text not null default '',
  vehicle_id bigint,
  kpi text not null default 'A',
  status text not null default '稼働'
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vehicle_id text not null,
  number text not null default '',
  inspection_expiry text not null default '',
  liability_expiry text not null default '',
  insurance_expiry text not null default '',
  oil_change_date text not null default '',
  oil_change_distance text not null default '',
  tire_change_date text not null default '',
  remarks text not null default ''
);

create table if not exists public.shifts (
  id bigint primary key,
  date text not null default '',
  area text not null,
  course text not null,
  driver_id bigint,
  vehicle_id bigint,
  start_time text not null default '',
  end_time text not null default '',
  delivery_count bigint,
  status text not null default '未配車'
);
